# Generated by Django 3.2.7 on 2021-09-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_auto_20210925_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='neighborhood',
            new_name='neighbourhood',
        ),
    ]
