# Generated by Django 3.2.7 on 2021-09-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='photo',
            field=models.ImageField(default='no photo', upload_to='photos'),
        ),
    ]
