# Generated by Django 3.2.7 on 2021-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0006_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(default='Names', max_length=100),
        ),
    ]
