# Generated by Django 3.2.7 on 2021-09-29 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbourhood', '0007_alter_admin_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Profile',
        ),
    ]
